/*
 The MIT License (MIT)
 Copyright © 2017 Ivan Rodriguez. All rights reserved.

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
 and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or substantial
 portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
 OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#import <XCTest/XCTest.h>

#import "IRCryptoProvider.h"
#import "IREnvironment.h"
#import "IREnvironment+Testing.h"
#import "IRErrors.h"
#import "IRKeyPairs.h"
#import "IRKeyTypes.h"
#import "IRProtocolConstants.h"
#import "IRSecretBytes.h"
#import "IRSodium.h"
#import "IRSodiumCryptoProvider.h"

/**
 LAYER 2 GATE — SPEC §3.2, §3.4, §4.4, §8.2, §13.1, §15.3.

 THE MOST IMPORTANT GATE IN THE PLAN, and the reason is structural rather than rhetorical: every
 test above this layer is SELF-CERTIFYING. A round-trip test passes when encrypt and decrypt are
 wrong in the same direction, which is exactly how v3 kept 23 green tests while X3DH silently
 collapsed to a single DH. The vectors below are EXTERNAL — published in RFC 5869, RFC 7748,
 RFC 8032 and RFC 8439 — so they cannot be satisfied by a self-consistent mistake.

 NOTHING DOWNSTREAM IS TRUSTWORTHY UNTIL THESE PASS. No protocol vector may be generated before
 this gate is green (§15.6 step 1), because a frozen vector generated by a subtly wrong primitive
 becomes normative for Java, Kotlin and Swift.

 Each test names the §15.3 vector id it will become when the generator runs at Layer 10.
 */
@interface IRPrimitivesSpec : XCTestCase
@property (nonatomic, strong) IRSodiumCryptoProvider *provider;
@end

@implementation IRPrimitivesSpec

- (void)setUp {
    [super setUp];

    XCTAssertTrue([IRSodium ensureInitialized:NULL], @"libsodium must initialize");

    NSError *error = nil;
    self.provider = [IRSodiumCryptoProvider productionProvider:&error];
    XCTAssertNotNil(self.provider, @"provider construction failed: %@", error);
    XCTAssertNil(error);
}

#pragma mark - Helpers

/// Hex -> NSData. Rejects odd lengths and non-hex digits by failing the test, so a typo in a
/// vector below surfaces as "bad vector" rather than as "primitive is broken".
- (NSData *)dataFromHex:(NSString *)hex {
    XCTAssertEqual(hex.length % 2, 0u, @"hex literal must have even length");

    NSMutableData *data = [NSMutableData dataWithCapacity:(hex.length / 2)];

    for (NSUInteger index = 0; index < hex.length; index += 2) {
        NSString *pair = [hex substringWithRange:NSMakeRange(index, 2)];
        NSScanner *scanner = [NSScanner scannerWithString:pair];
        unsigned int value = 0;

        XCTAssertTrue([scanner scanHexInt:&value], @"not hex: %@", pair);

        uint8_t byte = (uint8_t)value;
        [data appendBytes:&byte length:1];
    }

    return [data copy];
}

/// §15.5 rule 4 — all hex strings are lowercase, even length.
- (NSString *)hexFromData:(NSData *)data {
    const uint8_t *bytes = (const uint8_t *)data.bytes;
    NSMutableString *hex = [NSMutableString stringWithCapacity:(data.length * 2)];

    for (NSUInteger index = 0; index < data.length; index++) {
        [hex appendFormat:@"%02x", bytes[index]];
    }

    return [hex copy];
}

- (NSString *)hexFromSecret:(IRSecretBytes *)secret {
    return [self hexFromData:[NSData dataWithBytes:secret.constBytes length:secret.length]];
}

- (IRSecretBytes *)secretFromHex:(NSString *)hex {
    IRSecretBytes *secret = [[IRSecretBytes alloc] initWithData:[self dataFromHex:hex] guarded:NO];
    XCTAssertNotNil(secret);
    return secret;
}

- (IRX25519Private *)x25519PrivateFromHex:(NSString *)hex {
    NSError *error = nil;
    IRX25519Private *key = [IRX25519Private fromData:[self dataFromHex:hex] guarded:NO error:&error];
    XCTAssertNotNil(key, @"%@", error);
    return key;
}

- (IRX25519Public *)x25519PublicFromHex:(NSString *)hex {
    NSError *error = nil;
    IRX25519Public *key = [IRX25519Public fromData:[self dataFromHex:hex] error:&error];
    XCTAssertNotNil(key, @"%@", error);
    return key;
}

#pragma mark - RFC 5869 — HKDF-SHA256 (§3.2, vectors RFC5869-A1..A3)

/**
 RFC 5869 Appendix A.1 — basic case.

 §3.2: "Validate against the RFC 5869 Appendix A test vectors before running any protocol test."
 Extract, expand and the combined form are each checked, because §7.2's KDF_RK is a one-shot HKDF
 while the RFC publishes the intermediate PRK — a port that gets Extract right and Expand wrong
 fails only on the OKM.
 */
- (void)testRFC5869_A1 {
    IRSecretBytes *ikm = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];
    IRSecretBytes *salt = [self secretFromHex:@"000102030405060708090a0b0c"];
    NSData *info = [self dataFromHex:@"f0f1f2f3f4f5f6f7f8f9"];

    NSError *error = nil;
    IRSecretBytes *prk = [self.provider hkdfExtractWithSalt:salt ikm:ikm error:&error];

    XCTAssertNotNil(prk, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:prk],
                          @"077709362c2e32df0ddc3f0dc47bba6390b6c73bb50f9c3122ec844ad7c2b3e5");

    IRSecretBytes *okm = [self.provider hkdfExpandWithPRK:prk info:info outputLength:42 error:&error];

    XCTAssertNotNil(okm, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:okm],
                          @"3cb25f25faacd57a90434f64d0362f2a2d2d0a90cf1a5a4c5db02d56ecc4c5bf"
                          @"34007208d5b887185865");

    IRSecretBytes *combined = [self.provider hkdfWithSalt:salt
                                                     ikm:ikm
                                                    info:info
                                            outputLength:42
                                                   error:&error];

    XCTAssertNotNil(combined, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:combined], [self hexFromSecret:okm],
                          @"HKDF(salt,ikm,info,L) must equal Expand(Extract(salt,ikm),info,L)");
}

/// RFC 5869 Appendix A.2 — 80-byte inputs and an 82-byte output, which spans THREE Expand blocks.
- (void)testRFC5869_A2 {
    IRSecretBytes *ikm = [self secretFromHex:
        @"000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
        @"202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"
        @"404142434445464748494a4b4c4d4e4f"];
    IRSecretBytes *salt = [self secretFromHex:
        @"606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f"
        @"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"
        @"a0a1a2a3a4a5a6a7a8a9aaabacadaeaf"];
    NSData *info = [self dataFromHex:
        @"b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
        @"d0d1d2d3d4d5d6d7d8d9dadbdcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeef"
        @"f0f1f2f3f4f5f6f7f8f9fafbfcfdfeff"];

    NSError *error = nil;
    IRSecretBytes *prk = [self.provider hkdfExtractWithSalt:salt ikm:ikm error:&error];

    XCTAssertNotNil(prk, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:prk],
                          @"06a6b88c5853361a06104c9ceb35b45cef760014904671014a193f40c15fc244");

    IRSecretBytes *okm = [self.provider hkdfExpandWithPRK:prk info:info outputLength:82 error:&error];

    XCTAssertNotNil(okm, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:okm],
                          @"b11e398dc80327a1c8e7f78c596a49344f012eda2d4efad8a050cc4c19afa97c"
                          @"59045a99cac7827271cb41c65e590e09da3275600c2f09b8367793a9aca3db71"
                          @"cc30c58179ec3e87c14c01d5c1f3434f1d87");
}

/**
 RFC 5869 Appendix A.3 — zero-length salt and info.

 A nil salt is how this implementation spells "zero-length", and the next test proves that spelling
 agrees with Z32 exactly as §3.2 promises.
 */
- (void)testRFC5869_A3 {
    IRSecretBytes *ikm = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];

    NSError *error = nil;
    IRSecretBytes *prk = [self.provider hkdfExtractWithSalt:nil ikm:ikm error:&error];

    XCTAssertNotNil(prk, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:prk],
                          @"19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04");

    IRSecretBytes *okm = [self.provider hkdfExpandWithPRK:prk
                                                     info:[NSData data]
                                             outputLength:42
                                                    error:&error];

    XCTAssertNotNil(okm, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:okm],
                          @"8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d"
                          @"9d201395faa4b61a96c8");
}

/**
 HKDF-SALT-EQUIV — `HKDF-Extract(Z32, ikm) == HKDF-Extract("", ikm)`.

 §3.2 states this explicitly and asks that it NOT be treated as a divergence point: HMAC pads any
 key shorter than its 64-byte block with zeros, so a 32-zero-byte salt and an empty salt are the
 same HMAC key. Everywhere the specification writes `salt = Z32` — §8.1's KDF_MK and §6.3's SK — an
 implementation MAY pass either. Recording it as an executable assertion is what stops a reviewer
 in another port from "fixing" it in one direction.
 */
- (void)testHKDFSaltEquivalence_Z32VersusEmpty {
    IRSecretBytes *ikm = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];
    IRSecretBytes *z32 = [[IRSecretBytes alloc] initWithBytes:kIRZ32 length:(NSUInteger)kIRLenZ32];

    NSError *error = nil;
    IRSecretBytes *withZ32 = [self.provider hkdfExtractWithSalt:z32 ikm:ikm error:&error];
    IRSecretBytes *withNil = [self.provider hkdfExtractWithSalt:nil ikm:ikm error:&error];

    XCTAssertNotNil(withZ32);
    XCTAssertNotNil(withNil);
    XCTAssertEqualObjects([self hexFromSecret:withZ32], [self hexFromSecret:withNil],
                          @"SPEC 3.2: Z32 and an empty salt MUST produce an identical PRK");

    /* And it really is the RFC 5869 A.3 PRK, so "they agree" is not two identical wrong answers. */
    XCTAssertEqualObjects([self hexFromSecret:withZ32],
                          @"19ef24a32c717b167f33a91d6f648bdf96596776afdb6377ac434c1c293ccb04");
}

/**
 HKDF-EXPAND-64 — the two-block T(i) counter loop that §7.2's KDF_RK needs.

 §3.2 names omitting the second block "the most common hand-rolled-HKDF bug", and §7.2 splits the
 64-byte output into RK' = okm[0..32) and CK = okm[32..64). A single-block implementation produces a
 correct-looking 32-byte RK' and a wrong (or absent) chain key — the failure would first surface as
 "the second message does not decrypt", far from its cause.

 Two assertions, and the second is the load-bearing one: the first 32 bytes of a 64-byte expansion
 MUST equal a 32-byte expansion (T(1) is shared), while the second 32 bytes MUST differ from the
 first (T(2) is genuinely computed, not a repeat of T(1)).
 */
- (void)testHKDFExpand64SpansTwoBlocks {
    IRSecretBytes *ikm = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];
    NSData *info = [NSData dataWithBytes:kIRLabelRK length:(NSUInteger)kIRLenLabelRK];

    NSError *error = nil;
    IRSecretBytes *prk = [self.provider hkdfExtractWithSalt:nil ikm:ikm error:&error];
    XCTAssertNotNil(prk, @"%@", error);

    IRSecretBytes *long64 = [self.provider hkdfExpandWithPRK:prk
                                                        info:info
                                                outputLength:(NSUInteger)kIRLenKDFRKOutput
                                                       error:&error];
    IRSecretBytes *short32 = [self.provider hkdfExpandWithPRK:prk
                                                         info:info
                                                 outputLength:(NSUInteger)kIRLenHMACSHA256
                                                        error:&error];

    XCTAssertNotNil(long64, @"%@", error);
    XCTAssertNotNil(short32, @"%@", error);
    XCTAssertEqual(long64.length, 64u);

    NSString *long64Hex = [self hexFromSecret:long64];
    NSString *firstBlock = [long64Hex substringToIndex:64];
    NSString *secondBlock = [long64Hex substringFromIndex:64];

    XCTAssertEqualObjects(firstBlock, [self hexFromSecret:short32],
                          @"T(1) must be identical whether L is 32 or 64");
    XCTAssertNotEqualObjects(firstBlock, secondBlock,
                             @"T(2) must be computed, not a repeat of T(1) - SPEC 3.2");
}

/// §3.2 — HKDF-Expand's ceiling is 255 blocks. Above it, fail rather than silently truncate.
- (void)testHKDFExpandRejectsOutOfRangeLengths {
    IRSecretBytes *ikm = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];

    NSError *error = nil;
    IRSecretBytes *prk = [self.provider hkdfExtractWithSalt:nil ikm:ikm error:&error];
    XCTAssertNotNil(prk);

    XCTAssertNil([self.provider hkdfExpandWithPRK:prk info:[NSData data] outputLength:0 error:NULL]);
    XCTAssertNil([self.provider hkdfExpandWithPRK:prk
                                             info:[NSData data]
                                     outputLength:(255 * 32) + 1
                                            error:NULL]);
    XCTAssertNotNil([self.provider hkdfExpandWithPRK:prk
                                                info:[NSData data]
                                        outputLength:(255 * 32)
                                               error:NULL]);
}

#pragma mark - HMAC-SHA256 (§3.2, §7.3)

/**
 RFC 4231 test case 1, and the arbitrary-key-length property §7.3's KDF_CK shares with
 HKDF-Extract.

 libsodium's ONE-SHOT crypto_auth_hmacsha256 fixes the key at 32 bytes. RFC 4231 case 1 uses a
 20-byte key, so this test fails outright against the one-shot form — which is precisely why the
 provider uses init/update/final.
 */
- (void)testHMACSHA256_RFC4231_Case1 {
    IRSecretBytes *key = [self secretFromHex:@"0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b"];
    NSData *message = [@"Hi There" dataUsingEncoding:NSUTF8StringEncoding];

    NSError *error = nil;
    IRSecretBytes *mac = [self.provider hmacSHA256WithKey:key message:message error:&error];

    XCTAssertNotNil(mac, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:mac],
                          @"b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7");
}

/// RFC 4231 test case 6 — a 131-byte key, longer than HMAC's 64-byte block, so the key is hashed
/// first. The path §3.2's salt note depends on.
- (void)testHMACSHA256_RFC4231_Case6_OversizedKey {
    NSMutableString *keyHex = [NSMutableString string];
    for (NSUInteger index = 0; index < 131; index++) {
        [keyHex appendString:@"aa"];
    }

    IRSecretBytes *key = [self secretFromHex:keyHex];
    NSData *message = [@"Test Using Larger Than Block-Size Key - Hash Key First"
                       dataUsingEncoding:NSUTF8StringEncoding];

    NSError *error = nil;
    IRSecretBytes *mac = [self.provider hmacSHA256WithKey:key message:message error:&error];

    XCTAssertNotNil(mac, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:mac],
                          @"60e431591ee0b67f0d8a26aacbf5b77f8e0bc6213728c5140546040f0ee37f54");
}

#pragma mark - SHA-256 (§3.2, §6.2, §5.5)

/// FIPS 180-4 "abc". The construction §6.2 applies to the 259-byte TRANSCRIPT and §5.5 to the
/// 77-byte FP input.
- (void)testSHA256_FIPS180_4 {
    NSError *error = nil;
    NSData *digest = [self.provider sha256OfData:[@"abc" dataUsingEncoding:NSUTF8StringEncoding]
                                           error:&error];

    XCTAssertNotNil(digest, @"%@", error);
    XCTAssertEqualObjects([self hexFromData:digest],
                          @"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");

    NSData *empty = [self.provider sha256OfData:[NSData data] error:&error];
    XCTAssertEqualObjects([self hexFromData:empty],
                          @"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
}

#pragma mark - RFC 7748 — X25519 (§4.2, §4.4, vector RFC7748-X25519)

/**
 RFC 7748 §5.2, first vector.

 The input scalar is stored through IRX25519Private, which CLAMPS it at construction (§4.2). That
 changes no cryptographic output — RFC 7748 §5 clamps internally, so X25519(s, P) == X25519(clamp(s),
 P) — and the published output still matches. Worth noting that clamp(RFC 7748 scalar 1) is exactly
 the `IK_A_d_priv` literal in §15.5's worked example: `a546…9ac4` clamps to `a046…9a44`.
 */
- (void)testRFC7748_X25519_Vector1 {
    IRX25519Private *scalar =
        [self x25519PrivateFromHex:@"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"];
    IRX25519Public *point =
        [self x25519PublicFromHex:@"e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c"];

    NSError *error = nil;
    IRSecretBytes *shared = [self.provider x25519WithPrivateKey:scalar publicKey:point error:&error];

    XCTAssertNotNil(shared, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:shared],
                          @"c3da55379de9c6908e94ea4df28d084f32eccf03491c71f754b4075577a28552");

    /* §4.2 — the stored scalar is the clamped form, which is what reaches state-blob offsets 243
       and 274. Without this rule libsodium/CryptoKit and BouncyCastle write different bytes there
       for cryptographically identical state. */
    XCTAssertEqualObjects([self hexFromSecret:scalar],
                          @"a046e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449a44");
}

/**
 RFC 7748 §5.2, SECOND vector — and it is REJECTED at the type boundary, on purpose.

 Its u-coordinate ends in 0x93, so bit 255 is SET. §4.4 check 2 rejects that encoding with
 ERR_INVALID_PUBLIC_KEY before any scalar multiplication happens.

 THIS IS THE INJECTIVITY BREAK §4.4 EXISTS TO CLOSE, and the second half of the test demonstrates it
 rather than asserting it: clearing the high bit yields a DIFFERENT 32-byte wire encoding that
 produces the IDENTICAL DH output, because RFC 7748 §5 has X25519 ignore that bit and every library
 masks it internally. One actual key, two wire spellings. The transcript hash, SESSION_AD and the
 §7.6 skipped-key map key are all keyed on those raw bytes, so an attacker could flip the bit to
 mint a second distinct map key or a second distinct DHr for the same key, forcing spurious DH
 ratchets and unbounded state growth. Canonical encodings never set the bit, so rejecting costs
 nothing.
 */
- (void)testRFC7748_X25519_Vector2_HighBitEncodingIsRejected {
    NSString *withHighBit = @"e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493";
    NSString *masked      = @"e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a413";

    NSError *error = nil;
    IRX25519Public *rejected = [IRX25519Public fromData:[self dataFromHex:withHighBit] error:&error];

    XCTAssertNil(rejected, @"SPEC 4.4 check 2: pk[31] & 0x80 must be clear");
    XCTAssertEqual(error.code, IRErrorInvalidPublicKey);
    XCTAssertFalse([IRX25519Public dataIsValidEncoding:[self dataFromHex:withHighBit]]);
    XCTAssertTrue([IRX25519Public dataIsValidEncoding:[self dataFromHex:masked]]);

    IRX25519Private *scalar =
        [self x25519PrivateFromHex:@"4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d"];

    error = nil;
    IRSecretBytes *shared = [self.provider x25519WithPrivateKey:scalar
                                                      publicKey:[self x25519PublicFromHex:masked]
                                                          error:&error];

    XCTAssertNotNil(shared, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:shared],
                          @"95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957",
                          @"the masked encoding reproduces RFC 7748's published output - which is "
                          @"exactly why two encodings for one key had to be refused at the boundary");
}

/**
 X25519-ZERO — every small-order input MUST be rejected with ERR_SMALL_ORDER_KEY (§4.4 check 3).

 These four points all drive the DH output to all-zero. §4.4 requires the OR-accumulator check be
 performed by the implementation ITSELF, not delegated to the library, so that behaviour is uniform
 across ports: libsodium returns -1, BouncyCastle throws, the JDK throws, and CRYPTOKIT DOES
 NOTHING AT ALL — on Swift the accumulator is the only defence there is. A hard-coded blacklist of
 the twelve small-order points is explicitly forbidden as the sole check, because mistyping one of
 twelve 32-byte constants fails silently.

 Only points whose canonical encoding has bit 255 clear appear here; the rest are unreachable past
 §4.4 check 2, which the previous test covers.
 */
- (void)testX25519RejectsSmallOrderPoints {
    NSArray<NSString *> *smallOrderPoints = @[
        @"0000000000000000000000000000000000000000000000000000000000000000",  // order 1
        @"0100000000000000000000000000000000000000000000000000000000000000",  // order 4
        @"e0eb7a7c3b41b8ae1656e3faf19fc46ada098deb9c32b1fd866205165f49b800",  // order 8
        @"ecffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f",  // p-1, order 2
        @"edffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f",  // p, == 0
        @"eeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7f",  // p+1, == 1
    ];

    IRX25519Private *scalar =
        [self x25519PrivateFromHex:@"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"];

    for (NSString *pointHex in smallOrderPoints) {
        NSError *error = nil;
        IRSecretBytes *shared = [self.provider x25519WithPrivateKey:scalar
                                                          publicKey:[self x25519PublicFromHex:pointHex]
                                                              error:&error];

        XCTAssertNil(shared, @"small-order point must be refused: %@", pointHex);
        XCTAssertEqual(error.code, IRErrorSmallOrderKey, @"point %@", pointHex);
        XCTAssertEqualObjects(IRErrorNameForCode((IRErrorCode)error.code), @"ERR_SMALL_ORDER_KEY");
    }
}

/// The DH agreement property, on freshly generated pairs: X25519(a_priv, b_pub) ==
/// X25519(b_priv, a_pub). Self-certifying on its own, which is why it sits BELOW the RFC vectors
/// rather than standing in for them.
- (void)testX25519AgreementIsSymmetric {
    NSError *error = nil;
    IRX25519KeyPair *alice = [self.provider generateX25519KeyPairWithError:&error];
    IRX25519KeyPair *bob = [self.provider generateX25519KeyPairWithError:&error];

    XCTAssertNotNil(alice, @"%@", error);
    XCTAssertNotNil(bob, @"%@", error);

    IRSecretBytes *aliceView = [self.provider x25519WithPrivateKey:alice.privateKey
                                                         publicKey:bob.publicKey
                                                             error:&error];
    IRSecretBytes *bobView = [self.provider x25519WithPrivateKey:bob.privateKey
                                                       publicKey:alice.publicKey
                                                           error:&error];

    XCTAssertNotNil(aliceView, @"%@", error);
    XCTAssertNotNil(bobView, @"%@", error);
    XCTAssertTrue([aliceView isEqualToSecretBytes:bobView]);
    XCTAssertFalse([aliceView isAllZero]);
}

#pragma mark - RFC 8032 — pure Ed25519 (§3.4, §4.2, vectors RFC8032-ED25519, ED25519-SEED-EXPAND)

/**
 RFC 8032 §7.1 — the four published pure-Ed25519 vectors.

 A PORT USING THE PREHASHED API FAILS HERE, which is the entire reason these are in the gate. §3.4
 verified that libsodium's multi-part crypto_sign_init/_update/_final_create is Ed25519ph — the
 vendored crypto_sign.h line 23 reads `typedef crypto_sign_ed25519ph_state crypto_sign_state` — and
 v3 signed with it at IREncryptionService.m:431-433. Ed25519ph over these inputs produces entirely
 different 64-byte signatures, so this test is the difference between "our ports interoperate" and
 "signature verification fails in exactly the place §1.2 defines as an active MITM".

 The private key inputs are 32-byte SEEDS (§4.2). Since crypto_sign_detached reads 64 bytes and uses
 sk[32..64) as the public key A, this test simultaneously exercises the crypto_sign_seed_keypair
 expansion that §3.4 and §16.2 require — a port that hands the seed straight through reads 32 bytes
 out of bounds and produces a signature that verifies against nothing.
 */
- (void)assertEd25519VectorWithSeed:(NSString *)seedHex
                          publicKey:(NSString *)publicKeyHex
                            message:(NSString *)messageHex
                          signature:(NSString *)signatureHex {
    NSError *error = nil;

    IREd25519Private *seed = [IREd25519Private fromData:[self dataFromHex:seedHex]
                                                guarded:NO
                                                  error:&error];
    XCTAssertNotNil(seed, @"%@", error);

    NSData *message = [self dataFromHex:messageHex];

    /* ED25519-SEED-EXPAND: the seed alone reproduces the published public key. */
    IREd25519Public *derived = [self.provider ed25519PublicKeyForSeed:seed error:&error];
    XCTAssertNotNil(derived, @"%@", error);
    XCTAssertEqualObjects([derived hexString], publicKeyHex,
                          @"crypto_sign_seed_keypair must reproduce the published IK^s");

    /* And signing through that expansion is byte-identical to the JDK's and CryptoKit's seed-based
       APIs. RFC 8032 signing is deterministic and fully determined by the seed; there are not two
       legitimate encodings to reconcile. */
    IREd25519Signature *signature = [self.provider ed25519SignMessage:message
                                                            withSeed:seed
                                                               error:&error];
    XCTAssertNotNil(signature, @"%@", error);
    XCTAssertEqualObjects([signature hexString], signatureHex,
                          @"pure Ed25519 signature mismatch - a prehashed API fails HERE");

    XCTAssertTrue([self.provider ed25519VerifySignature:signature
                                              ofMessage:message
                                              publicKey:derived]);
}

- (void)testRFC8032_Ed25519_PureSignAndVerify {
    [self assertEd25519VectorWithSeed:@"9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60"
                            publicKey:@"d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a"
                              message:@""
                            signature:@"e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e0652249"
                                      @"01555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe246551414"
                                      @"38e7a100b"];

    [self assertEd25519VectorWithSeed:@"4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb"
                            publicKey:@"3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c"
                              message:@"72"
                            signature:@"92a009a9f0d4cab8720e820b5f642540a2b27b5416503f8fb3762223ebdb"
                                      @"69da085ac1e43e15996e458f3613d0f11d8c387b2eaeb4302aeeb00d291"
                                      @"612bb0c00"];

    [self assertEd25519VectorWithSeed:@"c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7"
                            publicKey:@"fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025"
                              message:@"af82"
                            signature:@"6291d657deec24024827e69c3abe01a30ce548a284743a445e3680d7db5a"
                                      @"c3ac18ff9b538d16f290ae67f760984dc6594a7c15e9716ed28dc027bec"
                                      @"eea1ec40a"];

    /* RFC 8032's SHA(abc) case. NOTE its public key ends 0xbf — bit 255 SET. That is legal and
       ordinary for Ed25519, where that bit is the sign of x (RFC 8032 §5.1.2), NOT the RFC 7748
       u-coordinate masking bit. If §4.4 checks 1–2 were applied to Ed25519 keys as well as X25519
       ones, roughly half of all valid identities would be rejected — an intermittent ~50% failure
       that looks exactly like a signature bug. This vector is the regression test for that
       scoping. */
    [self assertEd25519VectorWithSeed:@"833fe62409237b9d62ec77587520911e9a759cec1d19755b7da901b96dca3d42"
                            publicKey:@"ec172b93ad5e563bf4932c70e1245034c35467ef2efd4d64ebf819683467e2bf"
                              message:@"ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55"
                                      @"d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94"
                                      @"fa54ca49f"
                            signature:@"dc2a4459e7369633a52b1bf277839a00201009a3efbf3ecb69bea2186c26"
                                      @"b58909351fc9ac90b3ecfdfbc7c66431e0303dca179c138ac17ad9bef11"
                                      @"77331a704"];
}

/// Verification MUST fail closed on a tampered signature, a tampered message, and the wrong key.
- (void)testEd25519VerificationRejectsTampering {
    NSError *error = nil;
    IREd25519Private *seed =
        [IREd25519Private fromData:[self dataFromHex:
            @"4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb"]
                           guarded:NO
                             error:&error];
    IREd25519Public *publicKey = [self.provider ed25519PublicKeyForSeed:seed error:&error];
    NSData *message = [self dataFromHex:@"72"];

    IREd25519Signature *signature = [self.provider ed25519SignMessage:message
                                                            withSeed:seed
                                                               error:&error];
    XCTAssertNotNil(signature);
    XCTAssertTrue([self.provider ed25519VerifySignature:signature
                                              ofMessage:message
                                              publicKey:publicKey]);

    NSMutableData *tamperedSignatureBytes = [signature.data mutableCopy];
    ((uint8_t *)tamperedSignatureBytes.mutableBytes)[0] ^= 0x01;
    IREd25519Signature *tamperedSignature = [IREd25519Signature fromData:tamperedSignatureBytes
                                                                   error:&error];

    XCTAssertFalse([self.provider ed25519VerifySignature:tamperedSignature
                                               ofMessage:message
                                               publicKey:publicKey]);
    XCTAssertFalse([self.provider ed25519VerifySignature:signature
                                               ofMessage:[self dataFromHex:@"73"]
                                               publicKey:publicKey]);

    IREd25519KeyPair *other = [self.provider generateEd25519KeyPairWithError:&error];
    XCTAssertFalse([self.provider ed25519VerifySignature:signature
                                               ofMessage:message
                                               publicKey:other.publicKey]);
}

/// A generated identity round-trips: the seed reproduces the pair's own public key, and its
/// signature verifies.
- (void)testGeneratedEd25519PairIsSelfConsistent {
    NSError *error = nil;
    IREd25519KeyPair *pair = [self.provider generateEd25519KeyPairWithError:&error];

    XCTAssertNotNil(pair, @"%@", error);
    XCTAssertEqual(pair.seed.length, (NSUInteger)kIRLenEd25519Private,
                   @"SPEC 4.2: the nominal private key is the 32-byte SEED, never the 64-byte sk");
    XCTAssertFalse([pair.seed isAllZero]);

    IREd25519Public *derived = [self.provider ed25519PublicKeyForSeed:pair.seed error:&error];
    XCTAssertTrue([derived isEqualToEd25519Public:pair.publicKey]);

    NSData *message = [@"nuntius" dataUsingEncoding:NSUTF8StringEncoding];
    IREd25519Signature *signature = [self.provider ed25519SignMessage:message
                                                            withSeed:pair.seed
                                                               error:&error];
    XCTAssertNotNil(signature, @"%@", error);
    XCTAssertTrue([self.provider ed25519VerifySignature:signature
                                              ofMessage:message
                                              publicKey:pair.publicKey]);
}

#pragma mark - RFC 8439 — ChaCha20-Poly1305 IETF (§8.2, vector RFC8439-AEAD)

/**
 RFC 8439 §2.8.2, the published AEAD example.

 The 12-byte nonce pins the IETF construction: the non-IETF libsodium spelling takes 8 bytes and is
 a silent incompatibility (§3.3), and this vector is what makes picking it up by autocomplete a
 test failure rather than a field incident. The 16-byte Poly1305 tag is APPENDED, so the sealed
 output is `ciphertext ‖ tag` and `len(sealed) == len(pt) + 16` exactly (§8.2 — ChaCha20 is a stream
 cipher; there is no padding).
 */
- (void)testRFC8439_AEADSealAndOpen {
    NSData *plaintext = [self dataFromHex:
        @"4c616469657320616e642047656e746c656d656e206f662074686520636c6173"
        @"73206f66202739393a204966204920636f756c64206f6666657220796f75206f"
        @"6e6c79206f6e652074697020666f7220746865206675747572652c2073756e73"
        @"637265656e20776f756c642062652069742e"];
    NSData *associatedData = [self dataFromHex:@"50515253c0c1c2c3c4c5c6c7"];

    NSError *error = nil;
    IRMessageEncKey *key = [IRMessageEncKey fromData:[self dataFromHex:
        @"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"]
                                             guarded:NO
                                               error:&error];
    IRNonce *nonce = [IRNonce fromData:[self dataFromHex:@"070000004041424344454647"] error:&error];

    XCTAssertNotNil(key, @"%@", error);
    XCTAssertNotNil(nonce, @"%@", error);

    NSData *sealed = [self.provider aeadSealPlaintext:plaintext
                                                  key:key
                                                nonce:nonce
                                       associatedData:associatedData
                                                error:&error];

    XCTAssertNotNil(sealed, @"%@", error);
    XCTAssertEqual(sealed.length, plaintext.length + (NSUInteger)kIRLenAEADTag);
    XCTAssertEqualObjects([self hexFromData:sealed],
                          @"d31a8d34648e60db7b86afbc53ef7ec2a4aded51296e08fea9e2b5a736ee62d6"
                          @"3dbea45e8ca9671282fafb69da92728b1a71de0a9e060b2905d6a5b67ecd3b36"
                          @"92ddbd7f2d778b8c9803aee328091b58fab324e4fad675945585808b4831d7bc"
                          @"3ff4def08e4b7a9de576d26586cec64b6116"
                          @"1ae10b594f09e26a7e902ecbd0600691",
                          @"RFC 8439 2.8.2 ciphertext with the 16-byte tag appended");

    NSData *opened = [self.provider aeadOpenCiphertextAndTag:sealed
                                                         key:key
                                                       nonce:nonce
                                              associatedData:associatedData
                                                       error:&error];

    XCTAssertNotNil(opened, @"%@", error);
    XCTAssertEqualObjects(opened, plaintext);
}

/**
 Every tamper is ERR_AEAD_AUTH_FAILED, including a single flipped bit of ASSOCIATED DATA.

 That last case is what §8.5 buys: AD is `SESSION_AD ‖ the complete header`, so the version byte,
 the type byte and the flags are CRYPTOGRAPHICALLY ENFORCED rather than checked by an `if`. A
 tampered version byte is an authentication failure — a strictly stronger fix for defect 13 than
 adding validation code, and it comes free with the AEAD.
 */
- (void)testAEADRejectsEveryTamper {
    NSData *plaintext = [@"nuntius v4" dataUsingEncoding:NSUTF8StringEncoding];
    NSData *associatedData = [self dataFromHex:@"04010000"];

    NSError *error = nil;
    IRMessageEncKey *key = [IRMessageEncKey fromData:[self dataFromHex:
        @"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"]
                                             guarded:NO
                                               error:&error];
    IRNonce *nonce = [self.provider randomNonceWithError:&error];
    XCTAssertNotNil(nonce, @"%@", error);

    NSData *sealed = [self.provider aeadSealPlaintext:plaintext
                                                  key:key
                                                nonce:nonce
                                       associatedData:associatedData
                                                error:&error];
    XCTAssertNotNil(sealed, @"%@", error);

    // 1. A flipped ciphertext bit.
    NSMutableData *tamperedCiphertext = [sealed mutableCopy];
    ((uint8_t *)tamperedCiphertext.mutableBytes)[0] ^= 0x01;
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:tamperedCiphertext
                                                     key:key
                                                   nonce:nonce
                                          associatedData:associatedData
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);

    // 2. A flipped TAG bit.
    NSMutableData *tamperedTag = [sealed mutableCopy];
    ((uint8_t *)tamperedTag.mutableBytes)[sealed.length - 1] ^= 0x01;
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:tamperedTag
                                                     key:key
                                                   nonce:nonce
                                          associatedData:associatedData
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);

    // 3. A flipped ASSOCIATED DATA bit - here, the protocol version byte.
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:sealed
                                                     key:key
                                                   nonce:nonce
                                          associatedData:[self dataFromHex:@"03010000"]
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);

    // 4. The wrong nonce.
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:sealed
                                                     key:key
                                                   nonce:[self.provider randomNonceWithError:NULL]
                                          associatedData:associatedData
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);

    // 5. The wrong key.
    IRMessageEncKey *wrongKey = [IRMessageEncKey fromData:[self dataFromHex:
        @"00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"]
                                                  guarded:NO
                                                    error:NULL];
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:sealed
                                                     key:wrongKey
                                                   nonce:nonce
                                          associatedData:associatedData
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);

    // 6. Truncated below the tag width. Unreachable through the §10 gates, which guarantee at least
    //    HDR_LEN + 16 bytes, but reachable through §12.3's at-rest seal, which no gate covers.
    error = nil;
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:[sealed subdataWithRange:NSMakeRange(0, 8)]
                                                     key:key
                                                   nonce:nonce
                                          associatedData:associatedData
                                                   error:&error]);
    XCTAssertEqual(error.code, IRErrorAEADAuthFailed);
}

/// §10.4 — an empty plaintext is LEGAL. The type 0x01 minimum is 56 + 0 + 16, so the empty case is
/// on the wire, not a curiosity.
- (void)testAEADHandlesEmptyPlaintext {
    NSError *error = nil;
    IRMessageEncKey *key = [IRMessageEncKey fromData:[self dataFromHex:
        @"808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"]
                                             guarded:NO
                                               error:&error];
    IRNonce *nonce = [self.provider randomNonceWithError:&error];

    NSData *sealed = [self.provider aeadSealPlaintext:[NSData data]
                                                  key:key
                                                nonce:nonce
                                       associatedData:[NSData data]
                                                error:&error];

    XCTAssertNotNil(sealed, @"%@", error);
    XCTAssertEqual(sealed.length, (NSUInteger)kIRLenAEADTag);

    NSData *opened = [self.provider aeadOpenCiphertextAndTag:sealed
                                                         key:key
                                                       nonce:nonce
                                              associatedData:[NSData data]
                                                       error:&error];

    XCTAssertNotNil(opened, @"%@", error);
    XCTAssertEqual(opened.length, 0u);
}

#pragma mark - Randomness and the §13.1 tripwire

/**
 THE v3 DEFECT, AS AN EXECUTABLE TEST.

 A CSPRNG that FAILS must not leave a usable key behind. v3 wrote
 `__unused int result = SecRandomCopyBytes(...)` over an `NSMutableData dataWithLength:` buffer
 (IREncryptionService.m:476-481), and because -dataWithLength: zero-fills, an RNG failure produced
 an ALL-ZERO KEY with no signal at all — the canonical failing-open bug: everything works, both
 parties agree, and the session has no security whatsoever.
 */
- (void)testRNGFailurePropagatesRatherThanYieldingAZeroKey {
    IREnvironment *broken =
        [IREnvironment environmentWithRandomSource:[IRScriptedRandomSource failingSource]];

    NSError *error = nil;
    IRSodiumCryptoProvider *provider = [IRSodiumCryptoProvider providerWithEnvironment:broken
                                                                                 error:&error];
    XCTAssertNotNil(provider, @"%@", error);

    error = nil;
    XCTAssertNil([provider generateX25519KeyPairWithError:&error]);
    XCTAssertEqual(error.code, IRErrorRNGFailure);

    error = nil;
    XCTAssertNil([provider generateEd25519KeyPairWithError:&error]);
    XCTAssertEqual(error.code, IRErrorRNGFailure);

    error = nil;
    XCTAssertNil([provider randomNonceWithError:&error]);
    XCTAssertEqual(error.code, IRErrorRNGFailure);

    error = nil;
    XCTAssertNil([provider randomBytesOfLength:32 error:&error]);
    XCTAssertEqual(error.code, IRErrorRNGFailure);
}

/**
 THE SILENT BREAK — a CSPRNG that SUCCEEDS and returns zeros. No return-value check can catch it.

 §13.1: "Every freshly generated private key SHOULD additionally be checked with an all-zero test as
 a cheap tripwire before first use." This is what proves the tripwire is wired up.

 The X25519 case is the subtle one, and the assertion below is really about ORDERING. The §4.2 clamp
 sets `k[31] |= 0x40`, so an all-zero scalar becomes `00…0040` — NOT all-zero — the instant it is
 normalized. A tripwire applied after clamping can never fire. It has to run on the raw CSPRNG
 output, and it does.
 */
- (void)testAllZeroRNGOutputIsCaughtByTheTripwire {
    IREnvironment *silentlyBroken =
        [IREnvironment environmentWithRandomSource:[IRScriptedRandomSource zeroSource]];

    NSError *error = nil;
    IRSodiumCryptoProvider *provider = [IRSodiumCryptoProvider providerWithEnvironment:silentlyBroken
                                                                                 error:&error];
    XCTAssertNotNil(provider, @"%@", error);

    error = nil;
    XCTAssertNil([provider generateX25519KeyPairWithError:&error],
                 @"an all-zero scalar must be caught BEFORE the clamp masks it into 00..40");
    XCTAssertEqual(error.code, IRErrorRNGFailure);

    error = nil;
    XCTAssertNil([provider generateEd25519KeyPairWithError:&error]);
    XCTAssertEqual(error.code, IRErrorRNGFailure);
}

/// §15.5 rule 5 — a scripted source makes ephemeral keys and nonces reproducible, which is what
/// lets a frozen vector pin them. Exhaustion is a failure, never a wrap: cycling would hand the
/// same nonce to two AEAD calls under one key.
- (void)testScriptedRandomSourceIsDeterministicAndDoesNotWrap {
    NSData *script = [self dataFromHex:
        @"0102030405060708090a0b0c"
        @"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"];

    IREnvironment *scripted =
        [IREnvironment environmentWithRandomSource:[IRScriptedRandomSource sourceWithData:script]];

    NSError *error = nil;
    IRSodiumCryptoProvider *provider = [IRSodiumCryptoProvider providerWithEnvironment:scripted
                                                                                 error:&error];

    IRNonce *nonce = [provider randomNonceWithError:&error];
    XCTAssertNotNil(nonce, @"%@", error);
    XCTAssertEqualObjects([nonce hexString], @"0102030405060708090a0b0c");

    IRX25519KeyPair *pair = [provider generateX25519KeyPairWithError:&error];
    XCTAssertNotNil(pair, @"%@", error);
    XCTAssertEqualObjects([self hexFromSecret:pair.privateKey],
                          @"a046e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449a44",
                          @"the scripted scalar, clamped per SPEC 4.2");

    error = nil;
    XCTAssertNil([provider randomNonceWithError:&error], @"the script is exhausted");
    XCTAssertEqual(error.code, IRErrorRNGFailure);
}

/// A generated X25519 private key is stored clamped (§4.2, §12.2 rule 8) and its public half is the
/// scalar's own base multiple.
- (void)testGeneratedX25519PrivateKeysAreClamped {
    for (NSUInteger attempt = 0; attempt < 16; attempt++) {
        NSError *error = nil;
        IRX25519KeyPair *pair = [self.provider generateX25519KeyPairWithError:&error];

        XCTAssertNotNil(pair, @"%@", error);
        XCTAssertTrue([IRX25519Private bytesAreClamped:pair.privateKey.constBytes],
                      @"SPEC 12.2 rule 8 rejects an unclamped scalar at blob offsets 243 and 274");
        XCTAssertFalse([pair.privateKey isAllZero]);
        XCTAssertTrue([IRX25519Public highBitIsClear:pair.publicKey.constBytes],
                      @"SPEC 4.4 check 2 - a generated key must satisfy our own boundary rule");
    }
}

/// Guarded allocation is opt-in (§13.3, decision D3) and must not change the key's value semantics.
- (void)testGuardedGenerationProducesUsableKeys {
    NSError *error = nil;
    IRX25519KeyPair *guarded = [self.provider generateX25519KeyPairGuarded:YES error:&error];
    IRX25519KeyPair *plain = [self.provider generateX25519KeyPairWithError:&error];

    XCTAssertNotNil(guarded, @"%@", error);
    XCTAssertTrue(guarded.privateKey.isGuarded);
    XCTAssertFalse(plain.privateKey.isGuarded);

    IRSecretBytes *first = [self.provider x25519WithPrivateKey:guarded.privateKey
                                                     publicKey:plain.publicKey
                                                         error:&error];
    IRSecretBytes *second = [self.provider x25519WithPrivateKey:plain.privateKey
                                                      publicKey:guarded.publicKey
                                                          error:&error];

    XCTAssertNotNil(first, @"%@", error);
    XCTAssertTrue([first isEqualToSecretBytes:second]);

    IREd25519KeyPair *guardedSigning = [self.provider generateEd25519KeyPairGuarded:YES error:&error];
    XCTAssertNotNil(guardedSigning, @"%@", error);
    XCTAssertTrue(guardedSigning.seed.isGuarded);
}

#pragma mark - §10.5 — every failure sets the error, and no path dereferences a NULL one

/**
 §10.5: "Every failure path MUST set the error out-parameter, and MUST NOT dereference a null one."

 v3's aeEncryptSimpleData: and aeDecryptSimpleData: both wrote `*error = err` with no null check,
 crashing every caller that passed NULL — which every test in the repository did. Each call below
 passes NULL on a KNOWN-FAILING path; the test passing at all is the assertion.
 */
- (void)testEveryFailurePathToleratesANullErrorOutParameter {
    IRX25519Private *scalar =
        [self x25519PrivateFromHex:@"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"];
    IRX25519Public *smallOrder =
        [self x25519PublicFromHex:@"0000000000000000000000000000000000000000000000000000000000000000"];

    XCTAssertNil([self.provider x25519WithPrivateKey:scalar publicKey:smallOrder error:NULL]);
    XCTAssertNil([self.provider hkdfExpandWithPRK:[self secretFromHex:@"00"]
                                             info:[NSData data]
                                     outputLength:32
                                            error:NULL]);
    XCTAssertNil([self.provider aeadOpenCiphertextAndTag:[NSData data]
                                                     key:[IRMessageEncKey fromData:[self dataFromHex:
                                                          @"808182838485868788898a8b8c8d8e8f"
                                                          @"909192939495969798999a9b9c9d9e9f"]
                                                                           guarded:NO
                                                                             error:NULL]
                                                   nonce:[self.provider randomNonceWithError:NULL]
                                          associatedData:[NSData data]
                                                   error:NULL]);

    IREnvironment *broken =
        [IREnvironment environmentWithRandomSource:[IRScriptedRandomSource failingSource]];
    IRSodiumCryptoProvider *provider = [IRSodiumCryptoProvider providerWithEnvironment:broken
                                                                                 error:NULL];
    XCTAssertNil([provider generateX25519KeyPairWithError:NULL]);
    XCTAssertNil([provider generateEd25519KeyPairWithError:NULL]);
}

/// §10.5 again, from the other side: an implementation MUST NOT return a null result with a null
/// error. Every failing call that IS given an out-parameter must populate it.
- (void)testNoFailurePathReturnsNilWithoutSettingAnError {
    NSError *error = nil;
    IRX25519Public *smallOrder =
        [self x25519PublicFromHex:@"0100000000000000000000000000000000000000000000000000000000000000"];
    IRX25519Private *scalar =
        [self x25519PrivateFromHex:@"a546e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449ac4"];

    XCTAssertNil([self.provider x25519WithPrivateKey:scalar publicKey:smallOrder error:&error]);
    XCTAssertNotNil(error);
    XCTAssertEqualObjects(error.domain, IRErrorDomain);

    error = nil;
    XCTAssertNil([self.provider randomBytesOfLength:0 error:&error]);
    XCTAssertNotNil(error);

    error = nil;
    XCTAssertNil([self.provider hkdfExpandWithPRK:[self secretFromHex:@"0b0b"]
                                             info:[NSData data]
                                     outputLength:32
                                            error:&error]);
    XCTAssertNotNil(error, @"a wrong-width PRK must be reported, not silently accepted");
}

#pragma mark - IREnvironment (§15.5 rules 5–6, §15.6)

/// §15.6 — the frozen suite must pass with the system clock ten years forward. That is only
/// possible if every clock read routes through one injectable source.
- (void)testFixedClockIsStableAndDerivesSecondsFromMilliseconds {
    IRFixedClock *clock = [IRFixedClock clockAtUnixMilliseconds:1767830400123ULL];

    XCTAssertEqual([clock nowUnixMilliseconds], 1767830400123ULL);
    XCTAssertEqual([clock nowUnixSeconds], 1767830400ULL);
    XCTAssertEqual([clock nowUnixMilliseconds], 1767830400123ULL, @"a fixed clock must not drift");

    [clock advanceByMilliseconds:(uint64_t)kIRSkippedTTLMs];
    XCTAssertEqual([clock nowUnixMilliseconds], 1767830400123ULL + 604800000ULL);

    [clock advanceBySeconds:1];
    XCTAssertEqual([clock nowUnixMilliseconds], 1767830400123ULL + 604800000ULL + 1000ULL);

    /* Saturating rather than wrapping: a wrap would land the clock in 1970 and invert every
       comparison the test was written to check. */
    [clock advanceByMilliseconds:UINT64_MAX];
    XCTAssertEqual([clock nowUnixMilliseconds], UINT64_MAX);

    IRFixedClock *fromSeconds = [IRFixedClock clockAtUnixSeconds:1767830400ULL];
    XCTAssertEqual([fromSeconds nowUnixMilliseconds], 1767830400000ULL);
    XCTAssertEqual([fromSeconds nowUnixSeconds], 1767830400ULL);
}

/// The production clock is a real Unix wall clock, and its two readings agree.
- (void)testProductionClockIsAPlausibleUnixTime {
    id<IRClock> clock = [IREnvironment production].clock;

    const uint64_t seconds = [clock nowUnixSeconds];
    const uint64_t milliseconds = [clock nowUnixMilliseconds];

    XCTAssertGreaterThan(seconds, 1767225600ULL, @"clock must be past 2026-01-01");
    XCTAssertEqualWithAccuracy((double)(milliseconds / 1000ULL), (double)seconds, 2.0);
}

/// The production environment is a shared singleton, and its random source really produces
/// varying output (a smoke test against a stub that returns constants).
- (void)testProductionEnvironmentIsSharedAndRandom {
    XCTAssertEqual([IREnvironment production], [IREnvironment production]);

    NSError *error = nil;
    NSData *first = [self.provider randomBytesOfLength:32 error:&error];
    NSData *second = [self.provider randomBytesOfLength:32 error:&error];

    XCTAssertNotNil(first, @"%@", error);
    XCTAssertNotNil(second, @"%@", error);
    XCTAssertNotEqualObjects(first, second);
    XCTAssertFalse(IRIsAllZero(first.bytes, first.length));
}

@end
